# Generated by Django 4.1 on 2024-04-09 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('security_question_1', models.TextField()),
                ('security_question_2', models.TextField()),
                ('security_question_1_answer', models.CharField(max_length=300)),
                ('security_question_2_answer', models.CharField(max_length=300)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CarouselImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carousel_image', models.ImageField(upload_to='carousel_images/')),
                ('carousel_title', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('carousel_description', models.CharField(blank=True, default='', max_length=300, null=True)),
            ],
            options={
                'db_table': 'carousel_images',
            },
        ),
        migrations.CreateModel(
            name='Coaching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('classes', models.CharField(max_length=600)),
                ('mode', models.CharField(max_length=20)),
                ('timings', models.CharField(max_length=200)),
                ('description', models.TextField(default='')),
                ('short_description', models.CharField(default='', max_length=200)),
                ('image', models.ImageField(default='', upload_to='coaching_thumbnails/')),
                ('syllabus', models.FileField(blank=True, default='', null=True, upload_to='coaching_syllabus/')),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'coaching',
            },
        ),
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('company_fav_icon', models.ImageField(blank=True, null=True, upload_to='fav_icons/')),
                ('company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('company_about_us', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'company_info',
            },
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=300, unique=True)),
                ('course_description', models.TextField()),
                ('course_short_description', models.CharField(max_length=350)),
                ('course_image', models.ImageField(upload_to='thumbnails/')),
                ('course_syllabus', models.FileField(default='', upload_to='course_syllabus/')),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Courses',
            },
        ),
        migrations.CreateModel(
            name='RequestCallBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('phone_number', models.CharField(max_length=15)),
                ('date', models.CharField(max_length=30)),
                ('time', models.CharField(max_length=30)),
                ('is_opened', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'request_call_back',
            },
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes_title', models.CharField(max_length=60)),
                ('notes', models.TextField()),
                ('written_on', models.CharField(default='', max_length=60)),
                ('edited_on', models.CharField(default='', max_length=60)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notes',
            },
        ),
        migrations.CreateModel(
            name='EnrolledStudents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_date', models.CharField(default='', max_length=60)),
                ('enrolled_time', models.CharField(default='', max_length=60)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.courses')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'enrolled_students',
            },
        ),
        migrations.CreateModel(
            name='Certificate_IDS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_number', models.CharField(max_length=40, unique=True)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
            options={
                'db_table': 'certificate_ids',
            },
        ),
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=60)),
                ('blog_content', models.TextField()),
                ('written_on', models.CharField(default='', max_length=60, null=True)),
                ('edited_on', models.CharField(default='', max_length=60)),
                ('is_published', models.BooleanField(default=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'blogs',
            },
        ),
    ]
