# Generated by Django 4.1 on 2024-04-09 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_companyuser_is_verified_userotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userotp',
            name='user',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
