# Generated by Django 4.1 on 2024-04-10 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_alter_courses_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='coaching',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
