# Generated by Django 4.1 on 2024-04-10 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_coaching_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coaching',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
