# Generated by Django 4.1 on 2024-04-10 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_alter_coaching_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='notes',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
