# Generated by Django 4.1 on 2024-04-15 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_blogs_slug_notes_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('email', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=14)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='favicon/')),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('currency_symbol', models.TextField(blank=True, default='₹')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'db_table': 'company',
            },
        ),
    ]
