# Generated by Django 4.1 on 2024-07-26 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0009_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolledstudents',
            name='is_read',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
