# Generated by Django 4.1 on 2024-07-27 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0011_carouselimages_carousel_redirect_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouselimages',
            name='is_mobile',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
