# Generated by Django 4.1 on 2024-07-27 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0012_carouselimages_is_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='tags',
            field=models.TextField(blank=True, default=''),
        ),
    ]
