# Generated by Django 4.1 on 2024-07-27 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0013_courses_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'course_categories',
            },
        ),
        migrations.AddField(
            model_name='courses',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, related_name='categories', to='homepage.coursecategories'),
        ),
    ]
