# Generated by Django 4.1 on 2024-08-01 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0014_coursecategories_courses_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoClassRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('time_slot', models.CharField(max_length=80)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='homepage.courses')),
            ],
            options={
                'db_table': 'demo_class_registeration',
            },
        ),
    ]
