# Generated by Django 4.1 on 2024-08-02 06:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0015_democlassregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('duration', models.DateField()),
                ('is_expired', models.BooleanField(blank=True, default=False)),
            ],
            options={
                'db_table': 'batches',
            },
        ),
        migrations.CreateModel(
            name='TimeSlots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_slot', models.TimeField()),
                ('is_available', models.BooleanField(blank=True, default=True)),
                ('is_for_demo', models.BooleanField(blank=True, default=False)),
            ],
            options={
                'db_table': 'time_slots',
            },
        ),
        migrations.AddField(
            model_name='democlassregistration',
            name='alternate_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='democlassregistration',
            name='date_of_birth',
            field=models.DateField(default='2020-02-02'),
        ),
        migrations.AddField(
            model_name='democlassregistration',
            name='gender',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.CreateModel(
            name='StudentID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webxter_student_id', models.IntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
            options={
                'db_table': 'students_id',
            },
        ),
        migrations.CreateModel(
            name='RegisterationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=15)),
                ('alternate_number', models.CharField(blank=True, default='', max_length=15, null=True)),
                ('student_id', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('higest_education_qualification', models.CharField(max_length=600)),
                ('institute_name', models.CharField(max_length=600)),
                ('privious_courses', models.TextField(blank=True, default='', null=True)),
                ('relevant_certifications', models.TextField(blank=True, default='', null=True)),
                ('is_returning_student', models.BooleanField(blank=True, default=False)),
                ('webxter_student_id', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('emergency_contact_name', models.CharField(max_length=255)),
                ('emergency_contact_number', models.CharField(max_length=15)),
                ('emergency_conatct_relationship', models.CharField(max_length=500)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='homepage.batches')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='homepage.courses')),
            ],
            options={
                'db_table': 'registeration_form',
            },
        ),
        migrations.AlterField(
            model_name='democlassregistration',
            name='time_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='homepage.timeslots'),
        ),
    ]
