# Generated by Django 4.1 on 2024-08-02 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0016_batches_timeslots_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='democlassregistration',
            old_name='phone_number',
            new_name='contact_number',
        ),
    ]
