# Generated by Django 4.1 on 2024-08-02 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0017_rename_phone_number_democlassregistration_contact_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeslots',
            old_name='time_slot',
            new_name='end_slot',
        ),
        migrations.AddField(
            model_name='timeslots',
            name='start_slot',
            field=models.TimeField(default='10:00'),
            preserve_default=False,
        ),
    ]
