# Generated by Django 4.1 on 2024-08-02 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0019_democlassregistration_date_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='democlassregistration',
            name='date_slot',
            field=models.CharField(default='', max_length=30),
        ),
    ]
