# Generated by Django 4.1 on 2024-08-02 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0020_alter_democlassregistration_date_slot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registerationform',
            old_name='emergency_conatct_relationship',
            new_name='emergency_contact_relationship',
        ),
    ]
