# Generated by Django 4.1 on 2024-08-05 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0022_rename_higest_education_qualification_registerationform_highest_education_qualification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='course_description',
        ),
        migrations.AddField(
            model_name='courses',
            name='benefits',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='courses',
            name='curriculum',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='courses',
            name='details',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='courses',
            name='featured_image',
            field=models.ImageField(default='', upload_to='featured_images/'),
        ),
        migrations.AddField(
            model_name='courses',
            name='overview',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='courses',
            name='summary',
            field=models.CharField(default='', max_length=200),
        ),
    ]
