# Generated by Django 4.1 on 2024-08-06 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0023_remove_courses_course_description_courses_benefits_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='benefits',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='courses',
            name='curriculum',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='courses',
            name='details',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='courses',
            name='overview',
            field=models.TextField(),
        ),
    ]
