# Generated by Django 4.1 on 2024-08-23 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0027_courses_is_featured_courses_is_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecategories',
            name='image',
            field=models.ImageField(blank=True, default='default_image.jpg', upload_to='category_thumbnails/'),
        ),
        migrations.AddField(
            model_name='coursecategories',
            name='is_featured',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
