# Generated by Django 4.1 on 2024-08-23 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0028_coursecategories_image_coursecategories_is_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecategories',
            name='image',
            field=models.ImageField(blank=True, default='category_thumbnails/default_image.jpg', upload_to='category_thumbnails/'),
        ),
    ]
