# Generated by Django 4.1 on 2024-08-23 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0029_alter_coursecategories_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='duration',
            field=models.IntegerField(default=6),
        ),
        migrations.AddField(
            model_name='courses',
            name='number_of_projects',
            field=models.IntegerField(default=1),
        ),
    ]
