# Generated by Django 4.1 on 2024-08-24 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0030_courses_duration_courses_number_of_projects'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarkDownFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='course_markdown_files/')),
                ('title', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'db_table': 'markdown_files',
            },
        ),
        migrations.AddField(
            model_name='courses',
            name='markdown_file',
            field=models.ManyToManyField(blank=True, null=True, related_name='markdown_files', to='homepage.markdownfiles'),
        ),
    ]
