# Generated by Django 4.1 on 2024-09-07 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0032_alter_markdownfiles_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate_ids',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='homepage.courses'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certificate_ids',
            name='email',
            field=models.EmailField(default='user@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
