# Generated by Django 4.1 on 2024-12-16 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0033_certificate_ids_course_certificate_ids_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='democlassregistration',
            name='created_at',
            field=models.DateField(auto_now_add=True, default='2024-12-16'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='democlassregistration',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='democlassregistration',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
