# Generated by Django 4.1 on 2024-12-21 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0034_democlassregistration_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificate_ids',
            old_name='student_id',
            new_name='student',
        ),
    ]
