# Generated by Django 4.1 on 2024-12-21 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0035_rename_student_id_certificate_ids_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate_ids',
            name='end_date',
            field=models.DateField(blank=True, default='2025-01-01', null=True),
        ),
        migrations.AddField(
            model_name='certificate_ids',
            name='start_date',
            field=models.DateField(blank=True, default='2025-01-01', null=True),
        ),
    ]
