# Generated by Django 4.1 on 2024-12-21 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0036_remove_certificate_ids_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate_ids',
            name='end_date',
            field=models.DateField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='certificate_ids',
            name='start_date',
            field=models.DateField(blank=True, default='', null=True),
        ),
    ]
