# Generated by Django 4.1 on 2024-12-21 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0038_remove_certificate_ids_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyuser',
            name='date_of_birth',
            field=models.DateField(default='1990-01-01'),
            preserve_default=False,
        ),
    ]
