# Generated by Django 4.1 on 2024-12-23 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0039_alter_companyuser_date_of_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscribers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('subscribed', models.BooleanField(blank=True, default=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'newsletter_subscribers',
            },
        ),
    ]
